plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'io.github.gregorgregor25.t1arc.backup'
version = '0.1.0'

android {
  namespace "io.github.gregorgregor25.t1arc.backup"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }
  lintOptions {
    abortOnError false
  }
}

dependencies {
  implementation 'androidx.activity:activity-ktx:1.11.0'
  testImplementation 'junit:junit:4.13.2'
}
