import { existsSync, readFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import path from 'node:path';

import { describe, expect, it } from 'vitest';

const require = createRequire(import.meta.url);
const root = process.cwd();
const canonicalMarker = '// @generated by with-t1arc-wear';
const wearInclude =
  "include ':wear', ':watchface-meridian', ':watchface-chronograph', ':watchface-atelier', ':watchface-pace', ':watchface-summit'";

const wearPlugin = require(
  path.join(root, 'plugins', 'with-t1arc-wear.js'),
) as ((config: object) => object) & {
  injectT1ArcWearProjects: (contents: string) => string;
};
const { injectT1ArcWearProjects } = wearPlugin;

function occurrences(source: string, value: string) {
  return source.split(value).length - 1;
}

describe('T1 Arc Wear Expo plugin identity', () => {
  it('replaces the retired three-face block without retaining the Orbit project', () => {
    const previous = canonicalMarker + "\n" +
      "include ':wear', ':watchface-meridian', ':watchface-chronograph', ':watchface-orbit'\n" +
      "project(':watchface-orbit').projectDir = new File(rootProject.projectDir, '../wear/watchface-orbit')\n";
    const next = injectT1ArcWearProjects(previous);
    expect(next).not.toContain('watchface-orbit');
    expect(next).toContain(wearInclude);
    expect(injectT1ArcWearProjects(next)).toBe(next);
  });
  it('keeps the Expo config plugin as a callable CommonJS export', () => {
    expect(typeof wearPlugin).toBe('function');
    expect(typeof injectT1ArcWearProjects).toBe('function');
  });

  it('uses the T1 Arc plugin path in Expo configuration', () => {
    const appConfig = JSON.parse(
      readFileSync(path.join(root, 'app.json'), 'utf8'),
    ) as { expo: { plugins: (string | [string, object])[] } };
    const pluginNames = appConfig.expo.plugins.map((plugin) =>
      Array.isArray(plugin) ? plugin[0] : plugin,
    );

    expect(
      pluginNames.filter((plugin) => plugin === './plugins/with-t1arc-wear'),
    ).toHaveLength(1);
    expect(
      existsSync(path.join(root, 'plugins', 'with-t1arc-wear.js')),
    ).toBe(true);
  });

  it('attaches every existing Wear project exactly once and is idempotent', () => {
    const initial = "rootProject.name = 'T1 Arc'\n";
    const once = injectT1ArcWearProjects(initial);

    expect(once).toContain(canonicalMarker);
    expect(occurrences(once, wearInclude)).toBe(1);
    for (const projectPath of [
      "../wear/companion",
      "../wear/watchface-meridian",
      "../wear/watchface-chronograph",
      "../wear/watchface-atelier",
      "../wear/watchface-pace",
      "../wear/watchface-summit",
      "../wear/watchface-push",
    ]) {
      expect(once).toContain(projectPath);
    }
    expect(injectT1ArcWearProjects(once)).toBe(once);
  });

  it('repairs duplicate and truncated generated blocks', () => {
    const canonicalBlock = injectT1ArcWearProjects('').trim();
    const duplicate = `rootProject.name = 'T1 Arc'\n\n${canonicalBlock}\n${canonicalBlock}\n`;
    const repairedDuplicate = injectT1ArcWearProjects(duplicate);

    expect(occurrences(repairedDuplicate, canonicalMarker)).toBe(1);
    expect(occurrences(repairedDuplicate, wearInclude)).toBe(1);

    const truncated = `rootProject.name = 'T1 Arc'\n\n${canonicalMarker}\n${wearInclude}\n`;
    const repairedTruncated = injectT1ArcWearProjects(truncated);
    expect(occurrences(repairedTruncated, canonicalMarker)).toBe(1);
    expect(occurrences(repairedTruncated, wearInclude)).toBe(1);
    for (const projectPath of [
      "../wear/companion",
      "../wear/watchface-meridian",
      "../wear/watchface-chronograph",
      "../wear/watchface-atelier",
      "../wear/watchface-pace",
      "../wear/watchface-summit",
      "../wear/watchface-push",
    ]) {
      expect(repairedTruncated).toContain(projectPath);
    }
    expect(injectT1ArcWearProjects(repairedTruncated)).toBe(
      repairedTruncated,
    );
  });

  it('checks one canonical Wear block in a generated Android tree when present', () => {
    const settingsPath = path.join(root, 'android', 'settings.gradle');
    if (!existsSync(settingsPath)) return;
    const settings = readFileSync(settingsPath, 'utf8');

    expect(settings).toContain(canonicalMarker);
    expect(occurrences(settings, wearInclude)).toBe(1);
  });
});
