// Generated by scripts/build_country_food_packs.py. Metro .db assets remain outside JS memory.
export const COUNTRY_PACK_ASSETS: Record<string, () => number> = {
  'ca-cnf': () => require('../../../assets/food-packs/ca-cnf-2026.db'),
  'fr-ciqual': () => require('../../../assets/food-packs/fr-ciqual-2025.db'),
  'de-bls': () => require('../../../assets/food-packs/de-bls-4.0-2025.db'),
  // eslint-disable-next-line @typescript-eslint/no-require-imports -- Metro resolves this audited compressed native asset.
  'us-usda-branded': () => require('../../../assets/food-packs/us-usda-branded-2026-04-30.db.gz'),
};
